### PR TITLE
Convert to Python3

### PR DESCRIPTION
**Pull request by icemac**
Maybe this PR helps to make progress.

@ralic Are you willing to contribute your changes back to this repos? If yes, could you please rebase your changes to the current `python3` branch to resolve the conflicts?

### CODE REVIEW

**Comment by ralic** [comment]
Sure, let me deal with that later!

**Comment by icemac** [comment]
This PR is superseded by #14 which already runs on Python 3.

**Comment by ralic** [comment]
Thanks, @icemac . We shall close this PR.

**Comment by dataflake** [comment]
Superceded by #14

**Pull request closed without merging**
