### PR TITLE
[WIP] Python 2 / 3 compatibility.

### PR DESCRIPTION
**Pull request by icemac**
#15 should be merged beforehand to get rid of the ZServer dependency to allow running the test on Python 3.

Closes #18.

### CODE REVIEW

**Comment by icemac** [comment]
To get the tests of this PR green, #15 should be fixed and merged here. This allows to reduce duplicate work on both branches.

**Comment by icemac** [comment]
I rebased this PR onto #15 after merging it to master. Currently some Python 2.7 tests are failing which are fine on master. I'll look into them over the next days.

**Comment by icemac** [comment]
Now testing against Python 3.6, too. These tests are currently allowed to fail. We are currently at:
`Total: 485 tests, 12 failures, 60 errors, 8 skipped in 0.847 seconds.`

**Comment by davisagli** [comment]
@icemac I worked on this and have the tests passing on Python 2 and 3. This currently requires a couple fixes in other packages which are checked out in buildout.cfg:

- https://github.com/zopefoundation/Zope/pull/273
- https://github.com/zopefoundation/Products.GenericSetup/commit/5ba6817fda5c770da83f0dd59bcf60a378a9d215

**Comment by icemac** [comment]
@davisagli Cool! Thank you for working on this. I think we can get the required changes merged at the Zope-4-Welcome-Sprint this week.

**Pull request merged**
